include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
custom_lint:
  rules:
