name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  pod_player: ^0.1.5
  pretty_dio_logger: ^1.3.1
  readmore: ^2.2.0
  riverpod_annotation: ^2.1.1
  timeago: ^3.4.0
  tmdb_client: 
    path: packages/tmdb_client

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
