name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.2.12
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.2
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
