include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
